[project]
name = "agentic-rag"
version = "0.1.0"
description = "Multi-agent RAG demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "httpx>=0.28.1",
    "langchain>=1.2.6",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "langchain-huggingface>=0.3.0",
    "langchain-openai>=0.3.0",
    "langchain-text-splitters>=1.1.0",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "sentence-transformers>=2.7.0",
    "torch==2.12.0+cu132",
    "torchvision==0.27.0+cu132",
    "uvicorn>=0.40.0",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "fastapi[standard]>=0.128.0",
    "isort>=7.0.0",
    "pylint>=4.0.4",
    "pytest>=8.3.2",
    "httpx>=0.27.0",
    "pytest-asyncio>=0.24.0",
]
[tool.setuptools.packages.find]
include = ["app*", "rag*", "agents*"]
exclude = ["documents*", "tests*"]

[tool.uv.sources]
torch = { index = "pytorch-cu132" }
torchvision = { index = "pytorch-cu132" }

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://mirrors.nju.edu.cn/pytorch/whl/cu132"  # 用南京大学的源
explicit = true